name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-all-dev

      - name: Build project
        run: |
          ./autogen.sh
          ./configure
          make

      - name: Run tests
        run: make check
