name: Junkcoin Build CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Junkcoin Core
        run: |
          ./autogen.sh
          ./configure --without-gui
          make -j$(nproc)
