name: Junkcoin Build CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Junkcoin Core
        run: |
          ./autogen.sh
          CXXFLAGS="-g -ggdb -O0 -DDEBUG_LOCKORDER" ./configure \
            --enable-debug \
            --with-gui \
            --with-daemon \
            --with-utils \
            --disable-bench
          make -j$(nproc)
